// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by buildergenerator

package goexoml

//NewHangup return a new Hangup pointer
func NewHangup() *Hangup {
	return new(Hangup)
}

//IHangup The interface that satisfies all the methods for this struct
type IHangup interface {
}

//AddHangup appends the verb to response
func (r *Response) AddHangup(hangup IHangup) *Response {
	r.Response = append(r.Response, hangup)
	return r
}
