// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by buildergenerator

package goexoml

//SetAction sets Action
func (__record__ *Record) SetAction(action string) *Record {
	__record__.Action = action
	return __record__
}

//SetMethod sets Method
func (__record__ *Record) SetMethod(method string) *Record {
	__record__.Method = method
	return __record__
}

//SetTimeout sets Timeout
func (__record__ *Record) SetTimeout(timeout int) *Record {
	__record__.Timeout = timeout
	return __record__
}

//SetFinishOnKey sets FinishOnKey
func (__record__ *Record) SetFinishOnKey(finishonkey string) *Record {
	__record__.FinishOnKey = finishonkey
	return __record__
}

//SetMaxLength sets MaxLength
func (__record__ *Record) SetMaxLength(maxlength int) *Record {
	__record__.MaxLength = maxlength
	return __record__
}

//SetTranscribe sets Transcribe
func (__record__ *Record) SetTranscribe(transcribe bool) *Record {
	__record__.Transcribe = transcribe
	return __record__
}

//SetTranscribeCallback sets TranscribeCallback
func (__record__ *Record) SetTranscribeCallback(transcribecallback string) *Record {
	__record__.TranscribeCallback = transcribecallback
	return __record__
}

//SetPlayBeep sets PlayBeep
func (__record__ *Record) SetPlayBeep(playbeep bool) *Record {
	__record__.PlayBeep = playbeep
	return __record__
}

//SetTrim sets Trim
func (__record__ *Record) SetTrim(trim string) *Record {
	__record__.Trim = trim
	return __record__
}

//NewRecord return a new Record pointer
func NewRecord() *Record {
	return new(Record)
}

//IRecord The interface that satisfies all the methods for this struct
type IRecord interface {
	SetAction(action string) *Record
	SetMethod(method string) *Record
	SetTimeout(timeout int) *Record
	SetFinishOnKey(finishonkey string) *Record
	SetMaxLength(maxlength int) *Record
	SetTranscribe(transcribe bool) *Record
	SetTranscribeCallback(transcribecallback string) *Record
	SetPlayBeep(playbeep bool) *Record
	SetTrim(trim string) *Record
}

//AddRecord appends the verb to response
func (r *Response) AddRecord(record IRecord) *Response {
	r.Response = append(r.Response, record)
	return r
}
