// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by buildergenerator

package goexoml

//SetMethod sets Method
func (__redirect__ *Redirect) SetMethod(method string) *Redirect {
	__redirect__.Method = method
	return __redirect__
}

//SetURL sets URL
func (__redirect__ *Redirect) SetURL(url string) *Redirect {
	__redirect__.URL = url
	return __redirect__
}

//NewRedirect return a new Redirect pointer
func NewRedirect() *Redirect {
	return new(Redirect)
}

//IRedirect The interface that satisfies all the methods for this struct
type IRedirect interface {
	SetMethod(method string) *Redirect
	SetURL(url string) *Redirect
}

//AddRedirect appends the verb to response
func (r *Response) AddRedirect(redirect IRedirect) *Response {
	r.Response = append(r.Response, redirect)
	return r
}
