// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by buildergenerator

package goexoml

//SetVoice sets Voice for Say struct instance
func (__say__ *Say) SetVoice(voice string) *Say {
	__say__.Voice = voice
	return __say__
}

//SetLanguage sets Language for Say struct instance
func (__say__ *Say) SetLanguage(language string) *Say {
	__say__.Language = language
	return __say__
}

//SetLoop sets Loop for Say struct instance
func (__say__ *Say) SetLoop(loop int) *Say {
	__say__.Loop = loop
	return __say__
}

//SetText sets Text for Say struct instance
func (__say__ *Say) SetText(text string) *Say {
	__say__.Text = text
	return __say__
}

//NewSay return a new Say pointer
func NewSay() *Say {
	return new(Say)
}

//ISay The interface that satisfies all the methods for this struct
//ISay asserts implementation of setters for all the fields of Say
type ISay interface {
	SetVoice(voice string) *Say
	SetLanguage(language string) *Say
	SetLoop(loop int) *Say
	SetText(text string) *Say
}

//AddSay appends the verb to response
func (r *Response) AddSay(say ISay) *Response {
	r.Response = append(r.Response, say)
	return r
}
