// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by buildergenerator

package goexoml

import (
	"errors"
)

var _ = errors.New("_")

// SetVoice sets Voice for Say struct instance
func (sayReceiver *Say) SetVoice(voice string) *Say {
	sayReceiver.Voice = voice
	return sayReceiver
}

// SetLanguage sets Language for Say struct instance
func (sayReceiver *Say) SetLanguage(language string) *Say {
	sayReceiver.Language = language
	return sayReceiver
}

// SetLoop sets Loop for Say struct instance
func (sayReceiver *Say) SetLoop(loop int) *Say {
	sayReceiver.Loop = loop
	return sayReceiver
}

// SetText sets Text for Say struct instance
func (sayReceiver *Say) SetText(text string) *Say {
	sayReceiver.Text = text
	return sayReceiver
}

// Setter returns setter function for the field given
func (sayReceiver *Say) Setter(field string) (setter func(interface{}) (*Say, error)) {
	switch field {
	case "Voice":
		setter = func(VoiceField interface{}) (*Say, error) {
			if VoiceValue, ok := VoiceField.(string); ok {
				return sayReceiver.SetVoice(VoiceValue), nil
			}
			return nil, errors.New("Invalid type Expected string ")
		}
	case "Language":
		setter = func(LanguageField interface{}) (*Say, error) {
			if LanguageValue, ok := LanguageField.(string); ok {
				return sayReceiver.SetLanguage(LanguageValue), nil
			}
			return nil, errors.New("Invalid type Expected string ")
		}
	case "Loop":
		setter = func(LoopField interface{}) (*Say, error) {
			if LoopValue, ok := LoopField.(int); ok {
				return sayReceiver.SetLoop(LoopValue), nil
			}
			return nil, errors.New("Invalid type Expected int ")
		}
	case "Text":
		setter = func(TextField interface{}) (*Say, error) {
			if TextValue, ok := TextField.(string); ok {
				return sayReceiver.SetText(TextValue), nil
			}
			return nil, errors.New("Invalid type Expected string ")
		}
	}
	return
}

// NewSay return a new Say pointer
func NewSay() *Say {
	return new(Say)
}

// ISay The interface that satisfies all the methods for this struct
// ISay asserts implementation of setters for all the fields of Say
type ISay interface {
	SetVoice(voice string) *Say
	SetLanguage(language string) *Say
	SetLoop(loop int) *Say
	SetText(text string) *Say
	Setter(string) func(interface{}) (*Say, error)
}

// AddSay appends the verb to response
func (r *Response) AddSay(say ISay) *Response {
	r.Response = append(r.Response, say)
	return r
}
